# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='administrators',
        ),
        migrations.RemoveField(
            model_name='community',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='communityinvite',
            name='from_community',
        ),
        migrations.RemoveField(
            model_name='communityinvite',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='communitywallpost',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='communitywallpost',
            name='to',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='CommunityInvite',
        ),
        migrations.DeleteModel(
            name='CommunityWallPost',
        ),
    ]
