# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0004_community_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=300)),
                ('publication_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_topics', to='communities.Community')),
            ],
        ),
        migrations.AlterModelOptions(
            name='communitywallpost',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AlterField(
            model_name='communitywallpost',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_com_wallposts', to='communities.Community'),
        ),
    ]
