# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20170130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywallpost',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_wallposts', to='communities.Community'),
        ),
    ]
