# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20170130_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_message',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
