# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_discussion_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ('-publication_time',)},
        ),
    ]
