# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20170131_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='administrators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
