# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20170131_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='name',
            new_name='title',
        ),
    ]
