# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_auto_20170203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='text',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
