# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20170204_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
