# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_discussioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywallpost',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.Discussion'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
