# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_auto_20170221_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussioncomment',
            old_name='discussion',
            new_name='to_discussion',
        ),
    ]
