# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_auto_20170224_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitywallpost',
            old_name='to',
            new_name='to_community',
        ),
    ]
