# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_auto_20170224_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
