# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_name'),
        ('profiler', '0002_auto_20170129_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_members', to='communities.Community'),
        ),
    ]
