# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_profile_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_expanded',
            field=models.BooleanField(default=False, verbose_name='Розришений профіль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
