# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0005_auto_20170221_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_members', to='communities.Community'),
        ),
    ]
