# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0006_auto_20170224_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1, verbose_name='Стать'),
            preserve_default=False,
        ),
    ]
