# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0007_auto_20170226_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Чоловік'), ('W', 'Жінка')], max_length=1, verbose_name='Стать'),
        ),
    ]
