# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0002_auto_20170209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestep',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
