# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0003_auto_20170209_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_steps', to='courser.Course'),
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
