# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0004_auto_20170210_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestep',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
    ]
