# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0005_coursestep_sequence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_lecture', to='courser.CourseStep'),
        ),
    ]
