# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courser', '0007_auto_20170211_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_files')),
            ],
        ),
        migrations.CreateModel(
            name='IndependentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=15000)),
                ('course_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courser.CourseStep')),
            ],
        ),
        migrations.AddField(
            model_name='answerfile',
            name='independent_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courser.IndependentWork'),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
