# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0008_auto_20170213_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfile',
            name='file',
            field=models.FileField(upload_to='answers'),
        ),
    ]
