# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0010_dictation_dictationsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
