# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0011_dictation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictation',
            name='description',
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
