# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0012_auto_20170215_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestep',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
