# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0013_auto_20170217_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='audio',
            field=models.FileField(upload_to='dictations'),
        ),
    ]
