# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0016_auto_20170221_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationsolution',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
