# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0018_dictationsolution_comparison_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictationsolution',
            name='comparison_result',
            field=models.TextField(max_length=15000),
        ),
    ]
