# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0019_auto_20170222_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count_steps',
        ),
    ]
