# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0020_remove_course_count_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationsolution',
            name='errors_count',
            field=models.IntegerField(default=0),
        ),
    ]
