# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0021_dictationsolution_errors_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='dictations'),
        ),
    ]
