# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0025_answerfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfile',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
